apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment-busybox
  labels:
    app: myapp-busybox
  annotations:
    kubernetes.io/change-cause: "frontend validation update"
spec:
  selector:
    matchLabels:
      app: myapp-busybox
  replicas: 3
  template:
    metadata:
      name: mypod-busybox
      labels:
        app: myapp-busybox
    spec:
      containers:
      - name: mycontainer-busybox
        image: busybox
        command: ["sh", "-c"]
        args: ["sleep 3600"]
        env:
          - name: MY_ENV_VAR
            value: "Hello from Busybox!"
          - name: LOCATION
            value: "India"
