apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment-nginx
  labels:
    app: myapp-nginx
  annotations:
    kubernetes.io/change-cause: "Nginx Service"
spec:
  selector:
    matchLabels:
      app: myapp-nginx
  replicas: 3
  template:
    metadata:
      name: mypod-nginx
      labels:
        app: myapp-nginx
    spec:
      containers:
      - name: mycontainer-nginx
        image: nginx:latest # Use a different image for the example
        volumeMounts:
          - name: myvolume-nginx
            mountPath: /etc/nginx/nginx.conf # destination path in the container
            subPath: nginx-custom.conf
        ports:
          - containerPort: 1500 # Expose port 8080 for Nginx
      volumes:
        - name: myvolume-nginx
          hostPath:
            path: /data
            type: Directory

