apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
      app: example-app
  ports:
    - port: 80 # service port
      targetPort: 80 # Expose port 80 for Nginx
      nodePort: 30007 # NodePort to access the service externally