apiVersion: v1
kind: Service
metadata:
  name: myservice-nginx
spec:
  type: NodePort
  selector:
      app: myapp-nginx
  ports:
    - port: 80 # service port
      targetPort: 1500 # Expose port 80 for Nginx
      nodePort: 30007 # NodePort to access the service externally